/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.time.*;

import java.time.Duration;
import javax.swing.*;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.Timer;
import com.github.sarxos.webcam.*;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.*;
import com.google.zxing.common.HybridBinarizer;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import dao.ConnectionProvider;
import java.awt.BorderLayout;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import javax.imageio.ImageIO;





/**
 *
 * @author PCCS
 */
public class MarkAttendance extends javax.swing.JFrame implements Runnable, ThreadFactory {

private Webcam webcam = null;
private WebcamPanel panel = null;
private ExecutorService executor = Executors.newSingleThreadExecutor(this);
private volatile boolean running = true;

    /**
     * Creates new form MarkAttendance
     */
    public MarkAttendance() {
        initComponents();
      utility.BDUtility.setImage(this, "images/back.png", 1180, 627);
       // this.getRootPane().setBorder (BorderFactory.createMatteBorder (6, 6, 6, 6, Color. ORANGE));


    // 2. Set black border (4px on all sides)
    this.getRootPane().setBorder(
        BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK));
        int i = 0;
    
     startClock();
     initWebcam();
executor.execute(this);

    
    }
     private void startClock() {
        Timer timer = new Timer(1000, e -> updateTime()); // 1000 ms = 1 second
        timer.start();
    }
private void updateTime() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        lblTime.setText(sdf.format(new Date()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        WebcamPanel = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCheckInCheckOut = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1180, 627));
        setMinimumSize(new java.awt.Dimension(1180, 627));
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Mark Attendance");

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExit.setText("x");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WebcamPanelLayout = new javax.swing.GroupLayout(WebcamPanel);
        WebcamPanel.setLayout(WebcamPanelLayout);
        WebcamPanelLayout.setHorizontalGroup(
            WebcamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        WebcamPanelLayout.setVerticalGroup(
            WebcamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTime.setText("Time");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Time");

        lblCheckInCheckOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(264, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(WebcamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCheckInCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExit)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addComponent(WebcamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCheckInCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarkAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarkAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarkAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarkAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MarkAttendance().setVisible(true);
            }
        });
    }

private void initWebcam() {
    webcam = Webcam.getDefault();
    if (webcam == null) {
        JOptionPane.showMessageDialog(this, "No webcam detected");
        return;
    }

    Dimension size = WebcamResolution.VGA.getSize();
    webcam.setViewSize(size);
    panel = new WebcamPanel(webcam);
    panel.setPreferredSize(size);
    panel.setFPSDisplayed(true);

    WebcamPanel.setLayout(new BorderLayout());
    WebcamPanel.add(panel, BorderLayout.CENTER);
    WebcamPanel.revalidate();
    webcam.open();
}
    
 

@Override
public void run() {
    do {
        try {
            Thread.sleep(100);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        Result result = null;
        BufferedImage image = null;

        if (webcam.isOpen()) {
            if ((image = webcam.getImage()) == null) continue;

            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

            try {
                result = new MultiFormatReader().decode(bitmap);
            } catch (NotFoundException e) {
                // No QR code found
            }

            if (result != null) {
                String qrText = result.getText();
                System.out.println("Scanned: " + qrText);
                lblName.setText(qrText);  // Show full scan text (optional)

                // -------- Extract Email --------
                String[] lines = qrText.split("\\n");
                String email = "";

                for (String line : lines) {
                    if (line.toLowerCase().contains("email")) {
                        String[] parts = line.split(":");
                        if (parts.length > 1) {
                            email = parts[1].trim();
                        }
                    }
                }

                if (!email.isEmpty()) {
                    lblName.setText(email); // Show only email on label
                    try {
                        checkInCheckOut(email);
                        showUserImage(email);
                              
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid QR format. Email not found.");
                }
            }
        }
    } while (running);
}


private boolean checkInCheckOut(String email) throws HeadlessException, SQLException, IOException {
    Connection connection = ConnectionProvider.getCon();

    // STEP 1: Get userid from email
    int userId = -1;
    String userIdQuery = "SELECT id, image_path FROM userdetails WHERE email = ?";
    PreparedStatement pstUser = connection.prepareStatement(userIdQuery);
    pstUser.setString(1, email);
    ResultSet rsUser = pstUser.executeQuery();

    String imagePath = null;

    if (rsUser.next()) {
        userId = rsUser.getInt("id");
        imagePath = rsUser.getString("image_path");
    } else {
        JOptionPane.showMessageDialog(this, "Email not found in userdetails: " + email);
        return false;
    }
    rsUser.close();
    pstUser.close();

    // STEP 2: Display image if path is valid
// Load user image from src/images
if (imagePath != null && !imagePath.trim().isEmpty()) {
    try {
        // Use relative path to 'src/images' folder
        File imageFile = new File("src/images", imagePath); // Example: src/images/user1.jpg

        if (!imageFile.exists()) {
            System.err.println("Image not found at: " + imageFile.getAbsolutePath());
            lblImage.setIcon(null);
        } else {
            BufferedImage originalImage = ImageIO.read(imageFile);
            BufferedImage circularImage = createCircularImage(originalImage);
            lblImage.setIcon(new ImageIcon(circularImage));
        }
    } catch (IOException e) {
        System.err.println("Image loading error: " + e.getMessage());
        lblImage.setIcon(null);
    }
} else {
    lblImage.setIcon(null); // No image available
}

    // Continue with attendance logic
    String popUpHeader = null;
    String popUpMessage = null;
    Color color = null;

    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    LocalDate currentDate = LocalDate.now();
    LocalDateTime currentDateTime = LocalDateTime.now();

    // STEP 3: Check for existing attendance
    String selectQuery = "SELECT * FROM userattendance WHERE date = ? AND userid = ?";
    PreparedStatement pstSelect = connection.prepareStatement(selectQuery);
    pstSelect.setString(1, currentDate.format(dateFormatter));
    pstSelect.setInt(2, userId);
    ResultSet rs = pstSelect.executeQuery();

    if (rs.next()) {
        // Checkout logic
        String checkOutDateTimeStr = rs.getString("checkout");
        if (checkOutDateTimeStr != null && !checkOutDateTimeStr.isEmpty()) {
            popUpHeader = "Invalid Checkout";
            popUpMessage = "Already checked out for the day.";
            color = Color.RED;
            showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.ERROR_MESSAGE);
            rs.close();
            pstSelect.close();
            return false;
        }

        String checkInDateTimeStr = rs.getString("checkin");
        LocalDateTime checkInDateTime = LocalDateTime.parse(checkInDateTimeStr, dateTimeFormatter);
        Duration duration = Duration.between(checkInDateTime, currentDateTime);
        long hours = duration.toHours();
        long minutes = duration.minusHours(hours).toMinutes();
        long seconds = duration.minusHours(hours).minusMinutes(minutes).getSeconds();

        if (hours == 0 && minutes < 5) {
            long remainingMinutes = 4 - minutes;
            long remainingSeconds = 60 - seconds;
            popUpHeader = "Duration Warning";
            popUpMessage = String.format(
                "Work duration < 5 min. Try again in: %d minutes, %d seconds.",
                remainingMinutes, remainingSeconds);
            color = Color.ORANGE;
            showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.WARNING_MESSAGE);
            rs.close();
            pstSelect.close();
            return false;
        }

        // Update checkout
        String updateQuery = "UPDATE userattendance SET checkout = ?, workduration = ? WHERE date = ? AND userid = ?";
        PreparedStatement pstUpdate = connection.prepareStatement(updateQuery);
        pstUpdate.setString(1, currentDateTime.format(dateTimeFormatter));
        pstUpdate.setString(2, hours + " Hours and " + minutes + " Minutes");
        pstUpdate.setString(3, currentDate.format(dateFormatter));
        pstUpdate.setInt(4, userId);
        pstUpdate.executeUpdate();
        pstUpdate.close();

        popUpHeader = "Checked Out";
        popUpMessage = "Checked out at " + currentDateTime.format(dateTimeFormatter)
                + "\nDuration: " + hours + "h " + minutes + "m";
        color = Color.GREEN;
    } else {
        // New check-in
        String insertQuery = "INSERT INTO userattendance (userid, date, checkin) VALUES (?, ?, ?)";
        PreparedStatement pstInsert = connection.prepareStatement(insertQuery);
        pstInsert.setInt(1, userId);
        pstInsert.setString(2, currentDate.format(dateFormatter));
        pstInsert.setString(3, currentDateTime.format(dateTimeFormatter));
        pstInsert.executeUpdate();
        pstInsert.close();

        popUpHeader = "Checked In";
        popUpMessage = "Checked in at " + currentDateTime.format(dateTimeFormatter);
        color = Color.GREEN;
    }

    lblCheckInCheckOut.setHorizontalAlignment(SwingConstants.CENTER);
    lblCheckInCheckOut.setText(popUpHeader);
    lblCheckInCheckOut.setForeground(color);
    lblCheckInCheckOut.setBackground(Color.DARK_GRAY);
    lblCheckInCheckOut.setOpaque(true);

    showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.INFORMATION_MESSAGE);

    rs.close();
    pstSelect.close();
    return true;
}

private void showUserImage(String email) {
    try {
        Connection con = ConnectionProvider.getCon();
        String sql = "SELECT imagename FROM userdetails WHERE email = ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, email);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            String imgName = rs.getString("imagename");
            if (imgName != null && !imgName.trim().isEmpty()) {
                String imagePath = "src" + File.separator + "images" + File.separator + imgName;
                File imgFile = new File(imagePath);

                if (imgFile.exists()) {
                    BufferedImage img = ImageIO.read(imgFile);
                    Image scaled = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                    lblImage.setIcon(new ImageIcon(scaled));
                } else {
                    lblImage.setIcon(null);
                    JOptionPane.showMessageDialog(this, "❌ Image not found:\n" + imagePath);
                }
            } else {
                lblImage.setIcon(null);
                JOptionPane.showMessageDialog(this, "⚠️ No image name found in DB.");
            }
        }

        rs.close();
        ps.close();
        con.close();
    } catch (IOException ex) {
        lblImage.setIcon(null);
        JOptionPane.showMessageDialog(this, "⚠️ Error loading image:\n" + ex.getMessage());
    } catch (Exception ex) {
        lblImage.setIcon(null);
        JOptionPane.showMessageDialog(this, "⚠️ Unexpected error:\n" + ex.getMessage());
    }
}

// Show a JOptionPane that auto-closes after 5 seconds
private void showPopUpForCertainDuration(String popUpMessage, String popUpHeader, int messageType) throws HeadlessException {
    final JOptionPane optionPane = new JOptionPane(popUpMessage, messageType);
    final JDialog dialog = optionPane.createDialog(popUpHeader);

    Timer timer = new Timer(5000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            dialog.dispose();
            clearUserDetails();
        }
    });
    timer.setRepeats(false);
    timer.start();

    dialog.setVisible(true);
}
private BufferedImage createCircularImage(BufferedImage image) {
    int diameter = 285;

    // Resize original image to a square of given diameter
    BufferedImage resizedImage = new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2 = resizedImage.createGraphics();
    g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
    g2.drawImage(image, 0, 0, diameter, diameter, null);
    g2.dispose();

    // Create circular clipped image
    BufferedImage circularImage = new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2d = circularImage.createGraphics();
    Ellipse2D.Double circle = new Ellipse2D.Double(0, 0, diameter, diameter);
    g2d.setClip(circle);
    g2d.drawImage(resizedImage, 0, 0, null);
    g2d.dispose();

    return circularImage;
}

// Clear UI labels for next user
private void clearUserDetails() {
    lblCheckInCheckOut.setText("");
    lblCheckInCheckOut.setBackground(null);
    lblCheckInCheckOut.setForeground(null);
    lblCheckInCheckOut.setOpaque(false);

    lblName.setText("");
    lblImage.setIcon(null);
}


@Override
public void dispose() {
    running = false;
    if (webcam != null) {
        webcam.close();
    }
    super.dispose();
}

@Override
public Thread newThread(Runnable r) {
    Thread t = new Thread(r, "QR-Scanner-Thread");
    t.setDaemon(true); // optional, background thread
    return t;
}


 private javax.swing.JPanel jPanel2;

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WebcamPanel;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCheckInCheckOut;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables

    
}
