/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package forms;
import java.util.ArrayList;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import dao.ConnectionProvider;
import java.awt.Color;
import java.util.List; // Correct one
import java.text.SimpleDateFormat;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PCCS
 */
public class ViewAttendance extends javax.swing.JFrame {

    /** Creates new form ViewAttendance */
    public ViewAttendance() {
        initComponents();
        utility.BDUtility.setImage(this, "images/back.png", 1180, 610);
       // this.getRootPane().setBorder (BorderFactory.createMatteBorder (6, 6, 6, 6, Color. ORANGE));


    // 2. Set black border (4px on all sides)
    this.getRootPane().setBorder(
        BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK)
    );
   // jDateChooser2.setDateFormatString("yyyy-MM-dd");  // From date
   // jDateChooser3.setDateFormatString("yyyy-MM-dd");  // To date
jDateChooser2.setDateFormatString("yyyy-MM-dd");  // From date
jDateChooser3.setDateFormatString("yyyy-MM-dd");  // To date
   jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyReleased(java.awt.event.KeyEvent evt) {
        loadDataInTable();
    }
});
jDateChooser2.getDateEditor().addPropertyChangeListener(evt -> {
    if ("date".equals(evt.getPropertyName())) {
        loadDataInTable();
    }
});

jDateChooser3.getDateEditor().addPropertyChangeListener(evt -> {
    if ("date".equals(evt.getPropertyName())) {
        loadDataInTable();
    }
});

CheckBoxContact.addActionListener(evt -> loadDataInTable());
CheckBoxAddress.addActionListener(evt -> loadDataInTable());
CheckBoxState.addActionListener(evt -> loadDataInTable());
CheckBoxCountry.addActionListener(evt -> loadDataInTable());

       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DatainTable = new javax.swing.JTable();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        jLabel2To = new javax.swing.JLabel();
        jLabelsearch = new javax.swing.JLabel();
        jLabel4From = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        present = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CheckBoxContact = new javax.swing.JCheckBox();
        CheckBoxState = new javax.swing.JCheckBox();
        CheckBoxAddress = new javax.swing.JCheckBox();
        CheckBoxCountry = new javax.swing.JCheckBox();
        ButtonReset = new javax.swing.JButton();
        Absent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1180, 627));
        setMinimumSize(new java.awt.Dimension(1180, 627));
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExit.setText("x");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Attendance Track");

        DatainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(DatainTable);

        jDateChooser2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jDateChooser3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2To.setText("To");

        jLabelsearch.setText("Search");

        jLabel4From.setText("On / From");

        jLabel5.setText("Present");

        present.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        present.setForeground(new java.awt.Color(102, 255, 102));
        present.setText(".............");

        jLabel8.setText("Absent");

        CheckBoxContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxContact.setText("Contact");

        CheckBoxState.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxState.setText("Province");
        CheckBoxState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxStateActionPerformed(evt);
            }
        });

        CheckBoxAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxAddress.setText("Address");
        CheckBoxAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxAddressActionPerformed(evt);
            }
        });

        CheckBoxCountry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CheckBoxCountry.setText("Country");

        ButtonReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        Absent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Absent.setForeground(new java.awt.Color(255, 0, 51));
        Absent.setText(".............");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(present, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Absent, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CheckBoxContact)
                    .addComponent(CheckBoxAddress)
                    .addComponent(CheckBoxState)
                    .addComponent(CheckBoxCountry)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(ButtonReset)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232)
                        .addComponent(btnExit))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4From, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2To, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2To, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4From)
                    .addComponent(jLabelsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(present))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Absent))
                        .addGap(78, 78, 78)
                        .addComponent(CheckBoxContact)
                        .addGap(21, 21, 21)
                        .addComponent(CheckBoxAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckBoxState)
                        .addGap(27, 27, 27)
                        .addComponent(CheckBoxCountry)
                        .addGap(36, 36, 36)
                        .addComponent(ButtonReset)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void CheckBoxAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxAddressActionPerformed

    private void CheckBoxStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxStateActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
jTextField1.setText("");
jDateChooser2.setDate(null);
jDateChooser3.setDate(null);
CheckBoxContact.setSelected(false);
CheckBoxAddress.setSelected(false);
CheckBoxState.setSelected(false);
CheckBoxCountry.setSelected(false);
// CheckBoxUniqueRegId.setSelected(false); // If added
//loadDataInTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
          //  loadDataInTable();     // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        dao.tables.main(null); // ensure tables are created first
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ViewAttendance().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Absent;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JCheckBox CheckBoxAddress;
    private javax.swing.JCheckBox CheckBoxContact;
    private javax.swing.JCheckBox CheckBoxCountry;
    private javax.swing.JCheckBox CheckBoxState;
    private javax.swing.JTable DatainTable;
    private javax.swing.JButton btnExit;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2To;
    private javax.swing.JLabel jLabel4From;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelsearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel present;
    // End of variables declaration//GEN-END:variables

    
    
   
    
    
private void loadDataInTable() {
    // Step 1: Get input
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String searchText = jTextField1.getText().trim();
    Date fromDateRaw = jDateChooser2.getDate();
    Date toDateRaw = jDateChooser3.getDate();

    LocalDate fromDate = null, toDate = null;
    if (fromDateRaw != null)
        fromDate = fromDateRaw.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    if (toDateRaw != null)
        toDate = toDateRaw.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

    // If no search and no date filter, skip loading
    if (searchText.isEmpty() && fromDate == null && toDate == null) {
        ((DefaultTableModel) DatainTable.getModel()).setRowCount(0);
        present.setText("0");
        Absent.setText("0");
        return;
    }

    // Step 2: Build columns based on checkboxes
    List<String> columns = new ArrayList<>(Arrays.asList("ID", "Name", "Gender", "Email", "Date", "CheckIn", "Checkout", "Workduration"));
    boolean showContact = CheckBoxContact.isSelected();
    boolean showAddress = CheckBoxAddress.isSelected();
    boolean showState = CheckBoxState.isSelected();
    boolean showCountry = CheckBoxCountry.isSelected();

    if (showContact) columns.add("Contact");
    if (showAddress) columns.add("Address");
    if (showState) columns.add("State");
    if (showCountry) columns.add("Country");

    // Step 3: Build SQL
    StringBuilder sql = new StringBuilder("SELECT ud.id, ud.name, ud.gender, ud.email, ua.date, ua.checkin, ua.checkout, ua.workduration");
    if (showContact) sql.append(", ud.contact");
    if (showAddress) sql.append(", ud.address");
    if (showState) sql.append(", ud.state");
    if (showCountry) sql.append(", ud.country");
    sql.append(" FROM userdetails ud JOIN userattendance ua ON ud.id = ua.userid");

    boolean hasCondition = false;
    if (!searchText.isEmpty()) {
        sql.append(" WHERE (ud.name LIKE '%").append(searchText).append("%' OR ud.email LIKE '%").append(searchText).append("%')");
        hasCondition = true;
    }

    if (fromDate != null && toDate != null) {
        sql.append(hasCondition ? " AND " : " WHERE ");
        sql.append("ua.date BETWEEN '").append(fromDate).append("' AND '").append(toDate).append("'");
    } else if (fromDate != null) {
        sql.append(hasCondition ? " AND " : " WHERE ");
        sql.append("ua.date = '").append(fromDate).append("'");
    }

    // Step 4: Load data
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(columns.toArray());
    DatainTable.setModel(model);

    try (Connection con = ConnectionProvider.getCon();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery(sql.toString())) {

        long presentCount = 0;
        Set<String> emailSet = new HashSet<>();

        while (rs.next()) {
            List<Object> row = new ArrayList<>();
            row.add(rs.getInt("id"));
            row.add(rs.getString("name"));
            row.add(rs.getString("gender"));
            String email = rs.getString("email");
            row.add(email);
            emailSet.add(email);
            row.add(rs.getString("date"));
            row.add(rs.getString("checkin"));
            row.add(rs.getString("checkout"));
            row.add(rs.getString("workduration"));

            if (showContact) row.add(rs.getString("contact"));
            if (showAddress) row.add(rs.getString("address"));
            if (showState) row.add(rs.getString("state"));
            if (showCountry) row.add(rs.getString("country"));

            model.addRow(row.toArray());
            presentCount++;
        }

        // Step 5: Show present/absent only if filters applied
        present.setText(String.valueOf(presentCount));
        if (fromDate != null && toDate != null) {
            long weekdays = countWeekdays(fromDate, toDate);
            long absentCount = weekdays - presentCount;
            Absent.setText(String.valueOf(absentCount));
        } else {
            Absent.setText("0");
        }

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading data: " + ex.getMessage());
    }
}

private Long countWeekdays(LocalDate start, LocalDate end) {
    long count = 0;
    LocalDate date = start;
    while (!date.isAfter(end)) {
        DayOfWeek day = date.getDayOfWeek();
        if (day != DayOfWeek.SATURDAY && day != DayOfWeek.SUNDAY) {
            count++;
        }
        date = date.plusDays(1);
    }
    return count;
}

    

}
